# Generated by Django 5.2.10 on 2026-02-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_entry_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeentry',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Knowledge Entries'},
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
