# Generated by Django 5.2.10 on 2026-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List100Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('not_started', 'Chưa làm'), ('in_progress', 'Đang làm'), ('completed', 'Đã hoàn thành')], default='not_started', max_length=15, verbose_name='Trạng thái')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc')),
            ],
            options={
                'verbose_name': 'Mục tiêu trong 100 điều',
                'verbose_name_plural': '100 điều cần thực hiện',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
